server:
  port: 7001

#eureka:
#  instance:
#    hostname: localhost #eureka服务端的实例名称
#  client:
#    register-with-eureka: false #false表示不向注册中心注册自己
#    fetch-registry: false       #false表示自己端就是服务注册中心，客户端不能获取到注册-
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #设置与EurekaServer交互的地址，查询服务和注册服务都需要依赖这个地址
eureka:
  instance:
    hostname: eureka7001.com  #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false       #false表示自己端就是服务注册中心，客户端不能获取到注册-
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  #设置与EurekaServer交互的地址，查询服务和注册服务都需要依赖这个地址